name: "bmx.json"
on:
  push:
  schedule:
    - cron: "0 20 * * *"

jobs:
  generate_rss:
    runs-on: macOS-latest
    name: Generate RSS
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: RSS
        id: rss
        uses: ./
        with:
          yourInstagram: jsnmrs
          listOfInstagrams: crandallfbm,mark_burnett,bmx,radshare,drop_in_coffee,snakebitebmx,digbmx,jasonenns,tateroskelley,tajlucas,northeastbadboys,lookbackbmx,t1stagram,thejakeseeley,bmxdmc
          fileName: bmx.json
          feedTitle: BMX
      - name: Commit files
        if: ${{ success() && steps.rss.outputs.RSS_STATUS == 'success' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "Updated bmx.json"
          git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF}
